In [1]:
data_list = [1,2,3]


In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np


In [4]:
arr = np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [7]:
arr2 = np.array(data_list2)

In [8]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
arr3 = np.array([1,2,3,4,5])

In [10]:
arr3


array([1, 2, 3, 4, 5])

In [11]:
arr3[0]

1

In [12]:
arr3[4]

5

In [13]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr2[2,2]

90

In [15]:
arr2[0,1]

20

In [16]:
arr2[5,5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [28]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [29]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
np.random.randint(0,10)

2

In [31]:
np.random.randint(15)

9

In [32]:
np.random.randint(1,10,5)

array([8, 9, 5, 9, 9])

In [33]:
np.random.rand(5)

array([0.00138603, 0.50002514, 0.2056032 , 0.49300374, 0.7897421 ])

In [34]:
np.random.randn(5)

array([ 1.51673567, -1.56595834, -0.64582724, -0.70464953,  0.41237665])

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.reshape(4,4)

ValueError: cannot reshape array of size 25 into shape (4,4)

In [39]:
newArray = np.random.randint(1,100,10)

In [40]:
newArray

array([52, 44,  2, 67, 49, 12, 47,  2, 17, 80])

In [41]:
newArray.max()

80

In [42]:
newArray.min()

2

In [43]:
newArray.sum()

372

In [44]:
newArray.mean()

37.2

In [45]:
newArray.argmax()

9

In [46]:
newArray.argmin()

2

In [47]:
detArray = np.random.randint(1,100,25)

In [48]:
detArray

array([15, 69, 37, 79, 99, 46, 38, 40, 21, 91, 24, 82, 96, 97, 57, 37,  9,
       75, 54, 19, 48, 45, 85, 38, 24])

In [49]:
detArray = detArray.reshape(5,5)

In [50]:
detArray

array([[15, 69, 37, 79, 99],
       [46, 38, 40, 21, 91],
       [24, 82, 96, 97, 57],
       [37,  9, 75, 54, 19],
       [48, 45, 85, 38, 24]])

In [51]:
np.linalg.det(detArray)

176725776.0

In [52]:
detArray2 = np.array([[1,2],[3,4]])

In [53]:
detArray2

array([[1, 2],
       [3, 4]])

In [54]:
np.linalg.det(detArray2)

-2.0000000000000004

In [55]:
round(np.linalg.det(detArray2))

-2